# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-24 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_branch'),
        ('bpmn', '0023_auto_20180123_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='initiated_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Branch'),
        ),
    ]
